# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timer.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Timer(object):
    def setupUi(self, Timer):
        Timer.setObjectName(_fromUtf8("Timer"))
        Timer.resize(401, 235)
        self.buttonBox = QtGui.QDialogButtonBox(Timer)
        self.buttonBox.setGeometry(QtCore.QRect(110, 200, 176, 27))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.layoutWidget = QtGui.QWidget(Timer)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 371, 188))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.layoutWidget)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.FirstTimeLabel = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Sans [MONO]"))
        font.setPointSize(8)
        self.FirstTimeLabel.setFont(font)
        self.FirstTimeLabel.setObjectName(_fromUtf8("FirstTimeLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.FirstTimeLabel)
        self.FirstTime = QtGui.QSpinBox(self.layoutWidget)
        self.FirstTime.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.FirstTime.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.FirstTime.setMinimum(1)
        self.FirstTime.setMaximum(120)
        self.FirstTime.setSingleStep(1)
        self.FirstTime.setObjectName(_fromUtf8("FirstTime"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.FirstTime)
        self.FirstTextLabel = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Sans [MONO]"))
        font.setPointSize(8)
        self.FirstTextLabel.setFont(font)
        self.FirstTextLabel.setObjectName(_fromUtf8("FirstTextLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.FirstTextLabel)
        self.FirstText = QtGui.QLineEdit(self.layoutWidget)
        self.FirstText.setText(_fromUtf8(""))
        self.FirstText.setObjectName(_fromUtf8("FirstText"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.FirstText)
        self.SecondSoundLabel = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Sans [MONO]"))
        font.setPointSize(8)
        self.SecondSoundLabel.setFont(font)
        self.SecondSoundLabel.setObjectName(_fromUtf8("SecondSoundLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.SecondSoundLabel)
        self.StandingBox = QtGui.QGroupBox(self.layoutWidget)
        self.StandingBox.setTitle(_fromUtf8(""))
        self.StandingBox.setObjectName(_fromUtf8("StandingBox"))
        self.StandingFile = QtGui.QLineEdit(self.StandingBox)
        self.StandingFile.setGeometry(QtCore.QRect(0, 0, 161, 21))
        self.StandingFile.setText(_fromUtf8(""))
        self.StandingFile.setObjectName(_fromUtf8("StandingFile"))
        self.StandingFileBtn = QtGui.QPushButton(self.StandingBox)
        self.StandingFileBtn.setGeometry(QtCore.QRect(160, 0, 21, 21))
        self.StandingFileBtn.setObjectName(_fromUtf8("StandingFileBtn"))
        self.StandingPlayBtn = QtGui.QPushButton(self.StandingBox)
        self.StandingPlayBtn.setGeometry(QtCore.QRect(180, 0, 21, 21))
        self.StandingPlayBtn.setObjectName(_fromUtf8("StandingPlayBtn"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.StandingBox)
        self.SecondTextLabel = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Sans [MONO]"))
        font.setPointSize(8)
        self.SecondTextLabel.setFont(font)
        self.SecondTextLabel.setObjectName(_fromUtf8("SecondTextLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.SecondTextLabel)
        self.SecondTime = QtGui.QSpinBox(self.layoutWidget)
        self.SecondTime.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SecondTime.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.SecondTime.setMinimum(1)
        self.SecondTime.setMaximum(90)
        self.SecondTime.setSingleStep(1)
        self.SecondTime.setObjectName(_fromUtf8("SecondTime"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.SecondTime)
        self.SecondTimeLabel = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Sans [MONO]"))
        font.setPointSize(8)
        self.SecondTimeLabel.setFont(font)
        self.SecondTimeLabel.setObjectName(_fromUtf8("SecondTimeLabel"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.SecondTimeLabel)
        self.SecondText = QtGui.QLineEdit(self.layoutWidget)
        self.SecondText.setText(_fromUtf8(""))
        self.SecondText.setObjectName(_fromUtf8("SecondText"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.SecondText)
        self.FirstSoundLabel = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Sans [MONO]"))
        font.setPointSize(8)
        self.FirstSoundLabel.setFont(font)
        self.FirstSoundLabel.setObjectName(_fromUtf8("FirstSoundLabel"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.FirstSoundLabel)
        self.SittingBox = QtGui.QGroupBox(self.layoutWidget)
        self.SittingBox.setTitle(_fromUtf8(""))
        self.SittingBox.setObjectName(_fromUtf8("SittingBox"))
        self.SittingFile = QtGui.QLineEdit(self.SittingBox)
        self.SittingFile.setGeometry(QtCore.QRect(0, 0, 161, 21))
        self.SittingFile.setText(_fromUtf8(""))
        self.SittingFile.setObjectName(_fromUtf8("SittingFile"))
        self.SittingFileBtn = QtGui.QPushButton(self.SittingBox)
        self.SittingFileBtn.setGeometry(QtCore.QRect(160, 0, 21, 21))
        self.SittingFileBtn.setObjectName(_fromUtf8("SittingFileBtn"))
        self.SittingPlayBtn = QtGui.QPushButton(self.SittingBox)
        self.SittingPlayBtn.setGeometry(QtCore.QRect(180, 0, 21, 21))
        self.SittingPlayBtn.setObjectName(_fromUtf8("SittingPlayBtn"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.SittingBox)
        self.FirstTimeLabel.setBuddy(self.FirstTime)
        self.FirstTextLabel.setBuddy(self.FirstText)
        self.SecondSoundLabel.setBuddy(self.FirstText)
        self.SecondTextLabel.setBuddy(self.FirstTime)
        self.SecondTimeLabel.setBuddy(self.FirstText)
        self.FirstSoundLabel.setBuddy(self.FirstText)

        self.retranslateUi(Timer)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Timer.hide)
        QtCore.QMetaObject.connectSlotsByName(Timer)
        Timer.setTabOrder(self.FirstTime, self.FirstText)
        Timer.setTabOrder(self.FirstText, self.StandingFile)
        Timer.setTabOrder(self.StandingFile, self.StandingFileBtn)
        Timer.setTabOrder(self.StandingFileBtn, self.SecondTime)
        Timer.setTabOrder(self.SecondTime, self.SecondText)
        Timer.setTabOrder(self.SecondText, self.SittingFile)
        Timer.setTabOrder(self.SittingFile, self.SittingFileBtn)

    def retranslateUi(self, Timer):
        Timer.setWindowTitle(_translate("Timer", "EasyTimer Setup", None))
        self.FirstTimeLabel.setText(_translate("Timer", "Sitting Time (minutes)", None))
        self.FirstTextLabel.setText(_translate("Timer", "Sitting Text", None))
        self.SecondSoundLabel.setText(_translate("Timer", "Sitting Sound File", None))
        self.StandingFileBtn.setText(_translate("Timer", "...", None))
        self.StandingPlayBtn.setText(_translate("Timer", "▶", None))
        self.SecondTextLabel.setText(_translate("Timer", "Standing Time (minutes)", None))
        self.SecondTimeLabel.setText(_translate("Timer", "Standing Text", None))
        self.FirstSoundLabel.setText(_translate("Timer", "Sitting Sound File", None))
        self.SittingFileBtn.setText(_translate("Timer", "...", None))
        self.SittingPlayBtn.setText(_translate("Timer", "▶", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Timer = QtGui.QDialog()
    ui = Ui_Timer()
    ui.setupUi(Timer)
    Timer.show()
    sys.exit(app.exec_())

